### ISSUE TITLE
M1 Pro: 'NoneType' has no attribute 'name'

### ISSUE THREAD

**Issue by mateuspestana** [chychkan/DeepFaceLab_MacOS#67]
Hi,

I'm trying to train my model on my MacBook Pro M1 Pro, and I'm getting this error either I use SAEHD or Quick96. Am I doing something wrong?

```
Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

Running trainer.

[new] No saved models found. Enter a name of a new model : bolsobean
bolsobean

Model first run.
Error: 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/mateuspestana/Downloads/DeepFaceLab_MacOS/.dfl/DeepFaceLab/mainscripts/Trainer.py", line 46, in trainerThread
    model = models.import_model(model_class_name)(
  File "/Users/mateuspestana/Downloads/DeepFaceLab_MacOS/.dfl/DeepFaceLab/models/ModelBase.py", line 161, in __init__
    self.device_config = nn.DeviceConfig.GPUIndexes( force_gpu_idxs or nn.ask_choose_device_idxs(suggest_best_multi_gpu=True)) \
  File "/Users/mateuspestana/Downloads/DeepFaceLab_MacOS/.dfl/DeepFaceLab/core/leras/nn.py", line 215, in ask_choose_device_idxs
    best_device_indexes = [device.index for device in devices.get_equal_devices(devices.get_best_device()) ]
  File "/Users/mateuspestana/Downloads/DeepFaceLab_MacOS/.dfl/DeepFaceLab/core/leras/device.py", line 78, in get_equal_devices
    device_name = device.name
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by cantonalex** [comment]
Did you work this out? I'm having trouble installing tensorflow on my M1.

**Comment by chychkan** [comment]
I expect to get an M1 within next couple weeks and will look into it then.

**Comment by mateuspestana** [comment]
To install tensorflow, change on the requirements from tensorflow to tensorflow-macos and tensorflow-metal and it works, but still unable to train the model, because of GPU indexing.

**Comment by xfl0203** [comment]
> To install tensorflow, change on the requirements from tensorflow to tensorflow-macos and tensorflow-metal and it works, but still unable to train the model, because of GPU indexing.

.dfl/DeepFaceLab/core/leras/device.py
line27      replace to              all_devices = []

**Comment by xfl0203** [comment]
> To install tensorflow, change on the requirements from tensorflow to tensorflow-macos and tensorflow-metal and it works, but still unable to train the model, because of GPU indexing.

i can train model now, but it looks like run with cpu
